CREATE DATABASE CADASTRO
GO

USE CADASTRO
GO

CREATE TABLE CLIENTE(
	IDCLIENTE INT IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	CPF VARCHAR(20) NOT NULL,
	SEXO VARCHAR(20) NOT NULL
)
GO

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(IDCLIENTE)
GO